"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const types_classes_1 = require("./types & classes/types&classes");
const myMarketplace = new types_classes_1.Marketplace();
console.log("Hello World!");
console.log(types_classes_1.Marketplace);
const Sally = new types_classes_1.Seller("Sally");
console.log(Sally);
const Bob = new types_classes_1.Buyer("Bob");
console.log(Bob);
const List1 = new types_classes_1.Listing("House 1");
console.log(List1);
const List2 = new types_classes_1.Listing("House 2");
console.log(List2);
List2.publishListing();
console.log(List2);
List2.addBid({ bidAmount: 100n, bidder: Bob.username });
List2.addBid({ bidAmount: 12n, bidder: Bob.username });
console.log(List2);
